### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'pid'

### ISSUE THREAD

**Issue by y1026** [dobin/ffw#13]
Hello,

An error occurs after running ffw and after a certain period of time.

Thanks.

OS: Ubuntu 16_04 64bit.

```
INFO:root:Send pre data: 
DEBUG:root:  Sending pre message: 0
INFO:root:Send data: 
DEBUG:root:  Sending fuzzed message: 1
INFO:root:Restart server periodically: 10000
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/y1026/ffw/vulnserver/../fuzzer/fuzzingslave.py", line 186, in doActualFuzz
    serverManager.restart()
  File "/home/y1026/ffw/vulnserver/../fuzzer/simpleservermanager.py", line 72, in restart
    self.stop()
  File "/home/y1026/ffw/vulnserver/../fuzzer/simpleservermanager.py", line 64, in stop
    logging.info("Stop server PID: " + str(self.process.pid))
AttributeError: 'NoneType' object has no attribute 'pid'
```

**Comment by dobin** [comment]
Fixed by https://github.com/dobin/ffw/commit/01074bb09e00242614191e3b44d0929470f0e050
