### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'poll'

### ISSUE THREAD

**Issue by y1026** [dobin/ffw#14]
Hello,

An error occurs after running ffw and after a certain period of time.

Thanks.

OS: Ubuntu 16_04 64bit.

```
DEBUG:root:A fuzzing loop...
INFO:root:Open connection on localhost:20000
INFO:root:  Could not connect! Server is down: [Errno 111] Connection refused
INFO:root:Detected Crash (A)
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/y1026/ffw/vulnserver/../fuzzer/fuzzingslave.py", line 125, in doActualFuzz
    srvCrashData = serverManager.getCrashData()
  File "/home/y1026/ffw/vulnserver/../fuzzer/simpleservermanager.py", line 126, in getCrashData
    if self.process.poll():
AttributeError: 'NoneType' object has no attribute 'poll'
```

**Comment by dobin** [comment]
Did the fuzzing work before? I mean, was it possible to send some messages to the server?

Either FFW is not able to create the process, or the process exited before the status code could be retrieven.

**Comment by y1026** [comment]
@dobin 

Hello,

>Did the fuzzing work before? 
>I mean, was it possible to send some messages to the server?

Yes.

It worked well when I first started the program.

I found an error when going on for a long time (more than two days).

And I found a new error today.

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/y1026/ffw/vulnserver/../honggmode/honggslave.py", line 129, in doActualFuzz
    honggData = honggComm.readSocket()
  File "/home/y1026/ffw/vulnserver/../honggmode/honggcomm.py", line 33, in readSocket
    recv = self.sock.recv(4).decode()
error: [Errno 104] Connection reset by peer
```

Thanks.

**Comment by y1026** [comment]
@dobin 

Hello,

I have found a suspicious part.

When verified using the ps command, the server process is running.

However, it is impossible to connect to the server using the client.

So, I think the fuzzer causes various errors (network or process).

Thanks.

**Comment by dobin** [comment]
It appears that the fuzzing fucked the server so much, that it does not accept anymore connections, but did not crash. 

A possible solution is to specify a lower restart rate in fuzzying.py. Default is 10'000.
```
    # restart server every X fuzzing iterations
    "restart_server_every": 200,
```

**Comment by dobin** [comment]
Proposed fix: 
* When connecting to server, if it is not reachable, try again a few times, and then just restart it

**Comment by y1026** [comment]
Thanks for the reply.

I will try again, according to your advice. :+1:

**Comment by y1026** [comment]
@dobin 

Hello,

I can still see the error.

In my opinion, the "None" handling of the process is inadequate.

I am modifying the code and testing it.

Thanks.

Modification code: (simpleservermanager.py:64)

```
   def stop(self):
        """Stop the server"""
        if self.isDisabled:
            return
+	    if self.process is None:
+			return False
+	    else:
                        logging.info("Stop server PID: " + str(self.process.pid))
			self.process.terminate
```
Error Log
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/y1026/ffw/vulnserver/../fuzzer/fuzzingslave.py", line 186, in doActualFuzz
    serverManager.restart()
  File "/home/y1026/ffw/vulnserver/../fuzzer/simpleservermanager.py", line 72, in restart
    self.stop()
  File "/home/y1026/ffw/vulnserver/../fuzzer/simpleservermanager.py", line 64, in stop
    logging.info("Stop server PID: " + str(self.process.pid))
AttributeError: 'NoneType' object has no attribute 'pid'
```

**Comment by dobin** [comment]
Related :https://github.com/dobin/ffw/commit/0ba668d8c8165a84b6a524a3e350588d92533b55

How can such a little piece of code generate so much trouble :-)
