### ISSUE TITLE
Out of date instructions and/or not working

### ISSUE THREAD

**Issue by fgsch** [dobin/ffw#27]
fuzzing.py is no more

**Comment by fgsch** [comment]
With all due respect, are even testing these changes?

The docs are outdated, and this does not work using the provided instructions, e.g.:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/ffw/basicmode/basicslave.py", line 36, in doActualFuzz
    self.readDoActualfuzz()
AttributeError: 'BasicSlave' object has no attribute 'readDoActualfuzz'
Finished
```

**Comment by fgsch** [comment]
If the README file inside corpus is not removed:

```
Traceback (most recent call last):
  File "../ffw.py", line 21, in <module>
    sys.exit(main())
  File "../ffw.py", line 17, in main
    framework.realMain(None)
  File "/ffw/framework.py", line 143, in realMain
    ffwBasicFuzz(configManager, args)
  File "/ffw/framework.py", line 194, in ffwBasicFuzz
    basicmaster.doFuzz(config, args.gui)
  File "/ffw/basicmode/basicmaster.py", line 32, in doFuzz
    corpusManager.loadCorpusFiles()
  File "/ffw/common/corpusmanager.py", line 35, in loadCorpusFiles
    corpusData.readFromFile()
  File "/ffw/common/corpusdata.py", line 97, in readFromFile
    rawData = pickle.load(infile)
  File "/usr/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 927, in load_int
    val = long(data)
ValueError: invalid literal for long() with base 10: 'nput files\n'
```

**Comment by dobin** [comment]
I'm in the process of updating it; https://github.com/dobin/ffw/commit/add7b7181a16dbb6b7449573c11691e53ac0df97

The step-by-step guide may be slowly replaced by just referencing https://github.com/dobin/ffw-examples

**Comment by dobin** [comment]
Further improvements to the tutorial will come, it was just not on my priority list right now. Thanks for testing and feedback!
